task solution
machendos/lecture pull request #2
Opened 2018-10-07 19:35 UTC by DarthPigrum

2018-10-07 21:50 UTC, machendos requested changes

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +}
Зачем создавать эту функцию? Не проще просто в нужных местах вызывать ``arr.slice()`` ?

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +    arr = arr.sort(sort);
Just ```arr.sort(sort);```

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +    let i = 0;
Не нужно инициализировать переменную перед циклом-итератором коллекции

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +    for (i in arr) {
Это работать не будет
Допустим есть массив ```[1, 2, 3, 4, 5, 0, 0, 10]```
Условие фильтра: элемент не равен 0. Тогда дойдя до первого нуля, твой код его удалит, и сдвинет оставшуюся часть массива на один индекс влево. И значит 2-й ноль получит индекс первого. Но цикл, тем не менее, увеличит переменную цикла, и пойдёт дальше. Значит для второго нуля функция не запустится вовсе, и он останется в результирующем массиве. В таких случаях самый простой способ: создать цикл с 2-мя переменными: одна увеличивается каждую итерацию, вторую ты меняешь сам в теле, если это нужно

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +  if (shift) {
Просто ```result.push(arr.shift());```
И необходимо добавить проверку, что массив не пустой

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +    result.push(arrPop.pop());
Просто ```result.push(arr.pop());```
И тоже нужна проверка, что массив не пустой

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +  if (pop) arr.splice((arr.length - 1), 1);
Элемент уже удалён. Зачем его удалять опять?

2018-10-07 21:50 UTC, machendos commented on tasks/basics/task.js
> +class ArrayDo extends Array {
Класс не дописан. Нужно вызвать функцию-конструктор супер-класса

2018-10-07 21:59 UTC, DarthPigrum commented on tasks/basics/task.js
> +    let i = 0;
eslint попросил. конфиг отсюда: https://github.com/HowProgrammingWorks/Tools/blob/master/JavaScript/examples/.eslintrc.yml

2018-10-07 22:05 UTC, machendos commented on tasks/basics/task.js
> +    let i = 0;
```for (const i in arr)```

2018-10-07 22:08 UTC, DarthPigrum commented on tasks/basics/task.js
> +  if (shift) {
Если там один элемент, то он и первый, и последний, а так мы удалим его при взятии первого.

2018-10-07 22:10 UTC, DarthPigrum commented on tasks/basics/task.js
> +  if (pop) arr.splice((arr.length - 1), 1);
Удалён в безопасных копиях, которые были сделаны на случай единственного элемента

2018-10-07 22:13 UTC, DarthPigrum commented on tasks/basics/task.js
> +}
Там изначально был json-костыль, и я в одном месте изменил весь подход к копированию вместо редактирования каждого копирования. А так, в принципе - да: дальше буду через slice делать.

2018-10-08 21:12 UTC, machendos commented on tasks/basics/task.js
> +    let i = 0;
```for (let i = 0; i < arr.length;) {```

2018-10-08 21:12 UTC, machendos commented on tasks/basics/task.js
> +}
Функция осталась

2018-10-08 21:12 UTC, machendos commented on tasks/basics/task.js
> +  if (pop) arr.splice((arr.length - 1), 1);
И всё же, не понимаю зачем такой сложный ремув первого и последнего элемента. Оно реализуется в две строчки

2018-10-09 06:04 UTC, DarthPigrum commented on tasks/basics/task.js
> +  if (pop) arr.splice((arr.length - 1), 1);
Для побочного эффекта. Если здесь заменить arr.splice(0, 1) на arr.shift, то резаться оригинал не будет. Попробуй.

2020-05-25 11:20 UTC, closed without merging